import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Card from './component/foodcard'
import Darkmode from 'darkmode-js'

const Home: NextPage = () => {
  new Darkmode().showWidget();
  return (
    <div className={styles.container}>
      <Head>
        <title>Food Card-Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          Welcome to Food Card!
        </h1>
        <hr/>
        <Card/>
      </main>
    </div>
  )
}

export default Home
